<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'binary_operator_spaces' => true,
        'blank_line_after_opening_tag' => true,
        'concat_space' => ['spacing' => 'one'],
        'dir_constant' => true,
        'empty_return' => true,
        'escape_implicit_backslashes' => true,
        'heredoc_indentation' => true,
        'include_statement' => ['space' => 'none'],
        'increment_style' => ['style' => 'post'],
        'join_function_arguments_with_newline' => true,
        'language_level_type_declaration' => true,
        'list_syntax' => ['syntax' => 'short'],
        'lowercase_cast' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'method_argument_space' => true,
        'native_function_invocation' => ['include' => ['@all']],
        'new_with_braces' => true,
        'no_alias_functions' => true,
        'no_binary_string_operations' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_break_comment' => true,
        'no_closing_tag' => true,
        'no_duplicate_import_use_clause' => true,
        'no_else_if' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => ['tokens' => ['break', 'continue', 'return', 'throw']],
        'no_leading_import_statements' => true,
        'no_mixed_echo_print' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'no_null_property_initialization' => true,
        'no_short_bool_casts' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_superfluous_elseif' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_unneeded_control_parentheses' => true,
        'no_unused_imports' => true,
        'no_whitespace_before_semicolons' => true,
        'not_operator_with_space' => false,
        'operators_spaces' => true,
        'ordered_class_elements' => ['sort_algorithm' => 'alpha'],
        'php_unit_no_expectation_annotation' => true,
        'php_unit_test_case_static_method_calls' => ['call_type' => 'self'],
        'pow_to_exponentiation' => true,
        'property_assignment_without_null_coalescing' => true,
        'return_assignment' => true,
        'single_line_throw' => true,
        'switch_case_space' => true,
        'trailing_comma_in_multiline_array' => ['elements' => ['after_heredoc']],
        'type_cast_to_string' => true,
        'whitespace_after_comma_in_array' => ['space' => 'one'],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__ . '/src')
    );